name: aprendiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo.png"

flutter:
  uses-material-design: true
  assets:
      - assets/audios/Assimilacao1.mp3
      - assets/audios/Vaca.mp3
      - assets/audios/CachorroLatido.mp3
      - assets/audios/Galinha.mp3
      - assets/audios/GatoMiado.mp3
      - assets/audios/Assimilacao_1.mp3
      - assets/audios/Audicao_1.mp3
      - assets/audios/Memoria_1.mp3
      - assets/audios/Memoria_2.mp3
      - assets/imagens/
      - assets/fonts/
      - assets/icons/
      - lib/exemp/
      - lib/widgets/
      - lib/utils/
      - assets/icons/
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #   - family: Oilvare
    #     fonts:
    #       - asset: fonts/Oilvare Base.ttf
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package