// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTCKkAoRRQj5FOfkioLTUl2qM3caYExw',
    appId: '1:891939906457:web:c2ef29bc1903ad69262908',
    messagingSenderId: '891939906457',
    projectId: 'aprendiz-d08a7',
    authDomain: 'aprendiz-d08a7.firebaseapp.com',
    storageBucket: 'aprendiz-d08a7.firebasestorage.app',
    measurementId: 'G-EW4CX1499T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8mFuaNfjWA18n3yJ6x2iAn67KPRRsNSg',
    appId: '1:891939906457:android:83ccc57780bb73f3262908',
    messagingSenderId: '891939906457',
    projectId: 'aprendiz-d08a7',
    storageBucket: 'aprendiz-d08a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1oC8_7BkkexMqU6t7I8FuPK9NGdG33M',
    appId: '1:891939906457:ios:8b30337a6f4b319d262908',
    messagingSenderId: '891939906457',
    projectId: 'aprendiz-d08a7',
    storageBucket: 'aprendiz-d08a7.firebasestorage.app',
    iosBundleId: 'com.example.aprendiz',
  );

}